name: mate-runtime
version: 1.15.0~git
summary: MATE Desktop Runtime Environment
description: |
   The MATE Desktop Environment is the continuation of GNOME 2. It
   provides an intuitive and attractive desktop environment using traditional
   metaphors for Linux and other Unix-like operating systems.
   MATE is under active development to add support for new technologies while
   preserving a traditional desktop experience.
confinement: devmode

apps:
  # From mate-desktop
  mate-about:
    command: gtk-launch mate-about
    plugs:
      - home
      - x11

  # From mate-desktop
  mate-color-select:
    command: gtk-launch mate-color-select
    plugs:
      - home
      - x11
      
parts:
  mate-common:
    plugin: autotools
    source: https://github.com/mate-desktop/mate-common.git
    install-via: prefix
    build-packages:
      - gettext
      - intltool
      - libtool
      - pkg-config

  mate-desktop:
    plugin: autotools
    source: https://github.com/mate-desktop/mate-desktop.git
    after: [ mate-common, gtkconf ]
    configflags:
      - --disable-mpaste
      - --disable-schemas-compile
      - --disable-silent-rules
      - --disable-static
      - --with-gtk=3.0
    install-via: prefix
    build-packages:
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - libdconf-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libglib2.0-doc
      - libgtk-3-dev
      - libgtk-3-doc
      - libstartup-notification0-dev
      - libxml2-dev
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libstartup-notification0
      - libxml2
      - hicolor-icon-theme

  mate-user-guide:
    plugin: autotools
    source: https://github.com/mate-desktop/mate-user-guide.git
    after: [ mate-common ]
    install-via: prefix
    build-packages:
      - gettext
      - gtk-doc-tools
      - intltool
      - libtool
      - pkg-config
      - libglib2.0-dev
      - yelp-tools
    stage-packages:
      - yelp

# Fails to build, see README.md
#  libmatekbd:
#    plugin: autotools
#    source: https://github.com/mate-desktop/libmatekbd.git
#    after: [ mate-common, mate-desktop, gtkconf ]
#    configflags:
#      - --disable-silent-rules
#      - --disable-static
#      - --enable-introspection
#      - --with-gtk=3.0
#    install-via: prefix
#    build-packages:
#      - intltool
#      - libgirepository1.0-dev
#      - libglib2.0-dev
#      - libgtk-3-dev
#      - libxklavier-dev
#    stage-packages:
#      - iso-codes
#      - libglib2.0-0
#      - libgtk-3-0
#      - libxklavier16

  libmatemixer:
    plugin: autotools
    source: https://github.com/mate-desktop/libmatemixer.git
    after: [ mate-common ]
    configflags:
      - --disable-silent-rules
      - --disable-static
      - --enable-gtk-doc
    install-via: prefix
    build-packages:
      - libasound2-dev
      - libglib2.0-dev
      - libpulse-dev
    stage-packages:
      - iso-codes
      - libasound2
      - libglib2.0-0
      - libpulse0

  libmateweather:
    plugin: autotools
    source: https://github.com/mate-desktop/libmateweather.git
    after: [ mate-common ]
    configflags:
      - --disable-schemas-compile
      - --disable-silent-rules
      - --disable-static
      - --enable-gtk-doc
    install-via: prefix
    build-packages:
      - libglib2.0-dev
      - libgtk-3-dev
      - libsoup-gnome2.4-dev
      - libsoup2.4-dev
      - libxml2-dev
      - libxml2-utils
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libsoup-gnome2.4-1
      - libsoup2.4-1
      - libxml2