name: pluma
version: 1.15.0~git
summary: Pluma
description: |
   Pluma is a text editor which supports most standard editor features,
   extending this basic functionality with other features not usually
   found in simple text editors. Pluma is a graphical application which
   supports editing multiple text files in one window (known sometimes as
   tabs or MDI).
confinement: devmode

apps:
  pluma:
    command: gtk-launch pluma
    plugs:
      - home
      - x11

  pluma:
    plugin: autotools
    source: https://github.com/mate-desktop/pluma.git
    after: [ mate-common, mate-desktop, gtkconf ]
    configflags:
      - --disable-python
      - --disable-schemas-compile
      - --with-gtk=3.0
    install-via: prefix
    build-packages:
      - gtk-doc-tools
      - intltool
      - iso-codes
      - libenchant-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libgtksourceview-3.0-dev
      - libsm-dev
      - libx11-dev
      - libxml2-dev
      - yelp-tools
    stage-packages:
      - dconf-gsettings-backend
      - iso-codes
      - libenchant1c2a
      - libglib2.0-0
      - libgtk-3-0
      - libgtksourceview-3.0-1
      - libpango-1.0-0
      - libgdk-pixbuf2.0-0
      - libsm6
      - libx11-6
      - libxml2
      - yelp
      - zenity