name: mate-system-monitor
version: 1.15.0~git
summary: MATE System Monitor
description: |
    MATE system monitor allows you to graphically view and manipulate the running
    processes on your system.  It also provides an overview of available
    resources such as CPU and memory.
confinement: devmode

apps:
  mate-system-monitor:
    command: gtk-launch mate-system-monitor
    plugs:
      - home
      - network
      - x11

parts:
  mate-system-monitor:
    plugin: autotools
    source: https://github.com/mate-desktop/mate-system-monitor.git
    after: [ mate-common, gtkconf ]
    configflags:
      - --disable-schemas-compile
      - --disable-silent-rules
      - --libexecdir=/usr/lib/mate-system-monitor
      - --localstatedir=/var
      - --disable-static
      - --enable-systemd
      - --with-gtk=3.0
    install-via: prefix
    build-packages:
      - docbook-to-man
      - intltool
      - libglib2.0-dev
      - libglibmm-2.4-dev
      - libgtk-3-dev
      - libgtkmm-3.0-dev
      - libgtop2-dev
      - librsvg2-dev
      - libsystemd-dev
      - libwnck-3-dev
      - libxml2-dev
      - pkg-config
      - yelp-tools
    stage-packages:
      - gvfs
      - libglib2.0-0
      - libglibmm-2.4-1v5
      - libgtk-3-0
      - libgtkmm-3.0-1v5
      - libgtop2-common
      - librsvg2-common
      - libsystemd0
      - libwnck-3-0
      - libxml2
      - yelp